# Generated by Django 5.2 on 2025-09-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['role_id', 'menu_id'], name='unique_role_menu_active'),
        ),
    ]
