# Generated by Django 4.2 on 2025-09-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbluser",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Active"),
                    (2, "Inactive"),
                    (3, "Suspended"),
                    (4, "Pending"),
                    (5, "Locked"),
                ],
                default=4,
            ),
        ),
    ]
