# Generated by Django 5.2 on 2025-09-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_rolepermission_unique_role_menu_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='unique_role_menu',
        ),
    ]
