# Generated by Django 5.2 on 2025-10-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_passwordresetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
