# Generated by Django 5.2 on 2025-10-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_tbluser_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
