# Generated by Django 5.2 on 2025-09-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(default='Custom', max_length=50),
        ),
    ]
