# Generated by Django 5.2 on 2025-10-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_tbluser_is_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFailAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agent_browser', models.TextField(blank=True, null=True)),
                ('user_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_system_login_fail_attempts',
            },
        ),
    ]
