# Generated by Django 5.2 on 2025-09-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_role_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbluser',
            old_name='full_name',
            new_name='department',
        ),
        migrations.AddField(
            model_name='tbluser',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbluser',
            name='last_name',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbluser',
            name='position',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbluser',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='timeout',
            field=models.CharField(default=30),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
