# Generated by Django 5.2 on 2025-10-24 06:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_loginfailattempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUnlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('self', 'Self Unlock'), ('admin', 'Admin Unlock')], help_text='Indicates whether it was a self unlock or admin unlock.', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Time when the unlock was attempted.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from where the unlock was requested.', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent string of the request.', max_length=255, null=True)),
                ('success', models.BooleanField(default=False, help_text='Whether the unlock attempt was successful.')),
                ('details', models.TextField(blank=True, help_text='Any notes or reason for failure/success.', null=True)),
                ('unlocked_by', models.ForeignKey(blank=True, help_text='User who performed the unlock action (admin/staff), or blank for self.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock_performed', to=settings.AUTH_USER_MODEL)),
                ('unlocked_user', models.ForeignKey(blank=True, help_text='User whose account was attempted to be unlocked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Unlock Log',
                'verbose_name_plural': 'Account Unlock Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
