# Generated by Django 4.2 on 2025-09-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0006_departments"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="departments",
            table="auth_system_departments",
        ),
    ]
