# Generated by Django 5.2 on 2025-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_rename_full_name_tbluser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='timeout',
            field=models.CharField(default='30', max_length=100),
        ),
    ]
