# Generated by Django 5.2 on 2025-10-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_accountunlocklog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountunlocklog',
            table='auth_system_account_unlock_log',
        ),
        migrations.AlterModelTable(
            name='passwordresetlog',
            table='auth_system_password_reset_log',
        ),
    ]
