# Generated by Django 4.2 on 2025-09-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0007_alter_departments_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Departments",
            new_name="Department",
        ),
        migrations.AlterModelTable(
            name="department",
            table="auth_system_department",
        ),
    ]
