# Generated by Django 4.2 on 2025-09-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0008_rename_departments_department_alter_department_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
