# Generated by Django 5.2 on 2025-10-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_forgotpassword'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forgotpassword',
            table='auth_system_forgot_password',
        ),
    ]
