# Generated by Django 4.2 on 2025-09-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0007_alter_tbluser_timeout"),
        ("auth_system", "0009_alter_department_name"),
    ]

    operations = []
