# Generated by Django 4.2 on 2025-09-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0010_merge_20250918_1739"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbluser",
            name="role_id",
            field=models.ForeignKey(
                blank=True,
                db_column="role_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_role",
                to="auth_system.role",
            ),
        ),
    ]
