# Generated by Django 4.2 on 2025-09-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0011_alter_tbluser_role_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbluser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_column="department_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department_role",
                to="auth_system.department",
            ),
        ),
    ]
