# Generated by Django 5.2 on 2025-09-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0012_alter_tbluser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=255, null=True),
        ),
    ]
