# Generated by Django 5.2 on 2025-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("business_type", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=255, unique=True)),
                ("tax_id", models.CharField(max_length=20, unique=True)),
                ("website", models.CharField(max_length=255, unique=True)),
                ("industry", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("position", models.CharField(max_length=255)),
                ("account_status", models.CharField(max_length=100)),
                ("risk_level", models.CharField(max_length=100)),
                ("compliance_level", models.CharField(max_length=100)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "client_management",
            },
        ),
        migrations.CreateModel(
            name="RoleManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=255, unique=True)),
                ("access_level", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "role_management",
            },
        ),
        migrations.CreateModel(
            name="UserManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("role", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("session_timeout", models.IntegerField(default=30)),
                ("department", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_management",
            },
        ),
        migrations.CreateModel(
            name="VendorManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("internal_name", models.CharField(max_length=255)),
                ("base_url", models.CharField(max_length=255, unique=True)),
                ("contact_email", models.EmailField(max_length=255, unique=True)),
                ("priority", models.CharField(max_length=100)),
                ("timeout", models.IntegerField(default=30)),
                ("max_retries", models.IntegerField(default=3)),
                ("status", models.CharField(default="Active", max_length=50)),
                ("api_key", models.CharField(max_length=255, unique=True)),
                ("secret_key", models.CharField(max_length=255)),
                ("pricing_model", models.CharField(max_length=100)),
                (
                    "cost_per_request",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=50)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vendor_management",
            },
        ),
    ]
