# Generated by Django 5.2.6 on 2025-09-30 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255, unique=True)),
                ("business_type", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=255, unique=True)),
                ("tax_id", models.CharField(max_length=20, unique=True)),
                ("website", models.CharField(max_length=255, unique=True)),
                ("industry", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("position", models.CharField(max_length=255)),
                ("account_status", models.CharField(max_length=100)),
                ("risk_level", models.CharField(max_length=100)),
                ("compliance_level", models.CharField(max_length=100)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "kyc_client_management",
            },
        ),
        migrations.CreateModel(
            name="PanDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("client_id", models.CharField(blank=True, max_length=100, null=True)),
                ("pan_number", models.CharField(max_length=10, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("aadhaar_linked", models.BooleanField(null=True)),
                (
                    "masked_aadhaar",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("aadhaar_match", models.BooleanField(null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("dob_verified", models.BooleanField(null=True)),
                ("dob_check", models.BooleanField(null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("pan_status", models.CharField(blank=True, max_length=50, null=True)),
                ("is_salaried", models.BooleanField(null=True)),
                ("is_director", models.BooleanField(null=True)),
                ("is_sole_prop", models.BooleanField(null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("less_info", models.BooleanField(null=True)),
                ("profile_match", models.JSONField(blank=True, null=True)),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("pin_code", models.CharField(blank=True, max_length=10, null=True)),
                ("country", models.CharField(default="INDIA", max_length=100)),
                ("full_address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("created_by", models.IntegerField()),
            ],
            options={
                "db_table": "kyc_pan_details",
            },
        ),
        migrations.CreateModel(
            name="VendorManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=255, unique=True)),
                ("base_url", models.CharField(max_length=255, unique=True)),
                ("contact_email", models.EmailField(max_length=255, unique=True)),
                ("priority", models.IntegerField(default=30, unique=True)),
                ("timeout", models.IntegerField(default=30)),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(default="Active", max_length=50)),
                ("error_rate", models.FloatField(default=0.0)),
                ("response_time", models.FloatField(default=0.0)),
                ("downtime", models.FloatField(default=0.0)),
                ("health_score", models.FloatField(default=0.0)),
                (
                    "end_point_production",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "end_point_uat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "production_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uat_key", models.CharField(blank=True, max_length=255, null=True)),
                ("header", models.CharField(blank=True, max_length=255, null=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "kyc_vendor_management",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="PanRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pan_number", models.CharField(blank=True, max_length=20, null=True)),
                ("vendor", models.CharField(blank=True, max_length=50, null=True)),
                ("endpoint", models.CharField(max_length=200)),
                ("status_code", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("fail", "Fail")],
                        max_length=10,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pan_request_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=255, unique=True)),
                ("endpoint_path", models.CharField(max_length=255, unique=True)),
                ("http_method", models.CharField(max_length=10, unique=True)),
                ("descriptions", models.TextField(blank=True, null=True)),
                ("enable_api_endpoint", models.BooleanField(default=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supported_vendors",
                    models.ManyToManyField(
                        related_name="supported_apis",
                        to="kyc_api_gateway.vendormanagement",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_apis",
                        to="kyc_api_gateway.vendormanagement",
                    ),
                ),
            ],
            options={
                "db_table": "kyc_api_management",
            },
        ),
    ]
