# Generated by Django 5.2 on 2025-09-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoleManagement",
        ),
    ]
