# Generated by Django 4.2 on 2025-09-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendormanagement",
            name="header",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
