# Generated by Django 4.2 on 2025-09-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientmanagement",
            name="account_status",
        ),
        migrations.AddField(
            model_name="clientmanagement",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
