<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-15 12:59
=======
# Generated by Django 5.2 on 2025-09-15 12:26
>>>>>>> 1aa72d7e1f1bdbbc7a903e6914dcaa79cae39ddf

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('kyc_api_gateway', '0001_initial'),
=======
        ("kyc_api_gateway", "0001_initial"),
>>>>>>> 1aa72d7e1f1bdbbc7a903e6914dcaa79cae39ddf
    ]

    operations = [
        migrations.DeleteModel(
<<<<<<< HEAD
            name='RoleManagement',
=======
            name="RoleManagement",
>>>>>>> 1aa72d7e1f1bdbbc7a903e6914dcaa79cae39ddf
        ),
    ]
