# Generated by Django 5.2.6 on 2025-10-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmanagement",
            name="production_key",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="clientmanagement",
            name="uat_key",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
