# Generated by Django 4.2 on 2025-09-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0002_delete_rolemanagement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendormanagement",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="cost_per_request",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="pricing_model",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="secret_key",
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="downtime",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="error_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="health_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="response_time",
            field=models.FloatField(default=0.0),
        ),
    ]
