# Generated by Django 5.2.6 on 2025-10-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0002_clientmanagement_production_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendormanagement",
            old_name="vendor_name",
            new_name="vendor_namee",
        ),
    ]
