# Generated by Django 5.2.6 on 2025-10-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0002_panrequestlog_pan_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pandetails",
            name="pan_number",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
