# Generated by Django 4.2 on 2025-09-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0003_remove_vendormanagement_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendormanagement",
            name="api_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="secret_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
