# Generated by Django 5.2.6 on 2025-10-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0003_alter_pandetails_pan_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pandetails",
            options={"ordering": ["-created_at"]},
        ),
    ]
