# Generated by Django 5.2.6 on 2025-10-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0003_rename_vendor_name_vendormanagement_vendor_namee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendormanagement",
            old_name="vendor_namee",
            new_name="vendor_name",
        ),
    ]
