# Generated by Django 4.2 on 2025-09-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0003_alter_clientmanagement_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendormanagement",
            name="internal_name",
        ),
    ]
