# Generated by Django 4.2 on 2025-09-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "kyc_api_gateway",
            "0004_vendormanagement_api_key_vendormanagement_secret_key",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendormanagement",
            name="priority",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="ApiManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=255, unique=True)),
                ("endpoint_path", models.CharField(max_length=255)),
                ("http_method", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("enable_api_endpoint", models.BooleanField(default=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "default_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_apis",
                        to="kyc_api_gateway.vendormanagement",
                    ),
                ),
                (
                    "supported_vendors",
                    models.ManyToManyField(
                        related_name="supported_apis",
                        to="kyc_api_gateway.vendormanagement",
                    ),
                ),
            ],
            options={
                "db_table": "api_management",
            },
        ),
    ]
