# Generated by Django 5.2.6 on 2025-10-09 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0004_alter_pandetails_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panrequestlog",
            name="pan_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kyc_api_gateway.pandetails",
            ),
        ),
    ]
