# Generated by Django 5.2.6 on 2025-10-19 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0005_alter_panrequestlog_pan_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="KycMyServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("uat_url", models.CharField(max_length=255)),
                ("prod_url", models.CharField(max_length=255)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "kyc_my_services",
            },
        ),
        migrations.AddField(
            model_name="clientmanagement",
            name="prod_key",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="clientmanagement",
            name="uat_key",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="KycClientServicesManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_services",
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
                (
                    "myservice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_services",
                        to="kyc_api_gateway.kycmyservices",
                    ),
                ),
            ],
            options={
                "db_table": "kyc_client_services_management",
            },
        ),
    ]
