# Generated by Django 4.2 on 2025-09-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0005_alter_vendormanagement_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendormanagement",
            name="priority",
            field=models.CharField(max_length=100),
        ),
    ]
