# Generated by Django 4.2 on 2025-09-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0006_alter_vendormanagement_priority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apimanagement",
            old_name="description",
            new_name="descriptions",
        ),
    ]
