# Generated by Django 5.2.6 on 2025-10-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0007_electricitybill_billrequestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricitybill",
            name="bill_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="electricitybill",
            name="consumer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="electricitybill",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="electricitybill",
            name="full_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="electricitybill",
            name="reg_mobile_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="electricitybill",
            name="service_provider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
