# Generated by Django 4.2 on 2025-09-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0007_rename_description_apimanagement_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendormanagement",
            name="priority",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
