# Generated by Django 4.2 on 2025-09-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0008_alter_vendormanagement_priority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apimanagement",
            old_name="default_vendor",
            new_name="vendor",
        ),
    ]
