# Generated by Django 5.2.6 on 2025-10-08 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0008_electricitybill_bill_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KycNameMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=100, null=True)),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("name_1", models.CharField(blank=True, max_length=200, null=True)),
                ("name_2", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("match_status", models.BooleanField(blank=True, null=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "kyc_name_match",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NameMatchRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("name_1", models.CharField(blank=True, max_length=200, null=True)),
                ("name_2", models.CharField(blank=True, max_length=200, null=True)),
                ("vendor", models.CharField(blank=True, max_length=100, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("fail", "Fail")],
                        max_length=10,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="name_match_logs",
                        to="kyc_api_gateway.kycnamematch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "name_match_request_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
