# Generated by Django 5.2.6 on 2025-10-08 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0009_kycnamematch_namematchrequestlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoterDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        choices=[("karza", "Karza"), ("surepass", "Surepass")],
                        max_length=50,
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=100, null=True)),
                ("epic_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "input_voter_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "relation_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "relation_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("dob", models.CharField(blank=True, max_length=20, null=True)),
                ("age", models.CharField(blank=True, max_length=5, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "assembly_constituency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assembly_constituency_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "polling_station",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("part_no", models.CharField(blank=True, max_length=10, null=True)),
                ("part_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "slno_in_part",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ps_lat_long", models.CharField(blank=True, max_length=50, null=True)),
                ("name_v1", models.CharField(blank=True, max_length=255, null=True)),
                ("name_v2", models.CharField(blank=True, max_length=255, null=True)),
                ("name_v3", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "rln_name_v1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rln_name_v2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rln_name_v3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ps_name", models.CharField(blank=True, max_length=255, null=True)),
                ("house_no", models.CharField(blank=True, max_length=50, null=True)),
                ("last_update", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "parliamentary_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "parliamentary_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("st_code", models.CharField(blank=True, max_length=20, null=True)),
                ("voter_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "voter_detail",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoterRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=50, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("fail", "Fail")],
                        max_length=10,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voter_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_logs",
                        to="kyc_api_gateway.voterdetail",
                    ),
                ),
            ],
            options={
                "db_table": "voter_request_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
