# Generated by Django 5.2 on 2025-09-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0009_rename_default_vendor_apimanagement_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='notes',
        ),
    ]
