# Generated by Django 4.2 on 2025-09-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0010_remove_usermanagement_notes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserManagement",
        ),
    ]
