# Generated by Django 5.2.6 on 2025-10-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0011_rcdetails_rcrequestlog"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="rcrequestlog",
            table="kyc_rc_request_log",
        ),
    ]
