# Generated by Django 4.2 on 2025-09-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0011_delete_usermanagement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendormanagement",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="internal_name",
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apimanagement",
            name="endpoint_path",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="apimanagement",
            name="http_method",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="clientmanagement",
            name="company_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
