# Generated by Django 4.2 on 2025-09-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0012_remove_vendormanagement_display_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendormanagement",
            old_name="name",
            new_name="vendor_name",
        ),
    ]
