# Generated by Django 5.2.6 on 2025-10-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0012_alter_rcrequestlog_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="billrequestlog",
            table="kyc_bill_request_log",
        ),
    ]
