# Generated by Django 5.2 on 2025-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0013_rename_name_vendormanagement_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_source', models.CharField(help_text='vendor1 or vendor2', max_length=20)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhaar_linked', models.BooleanField(null=True)),
                ('masked_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhaar_match', models.BooleanField(null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('input_dob', models.CharField(blank=True, max_length=20, null=True)),
                ('dob_verified', models.BooleanField(null=True)),
                ('dob_check', models.BooleanField(null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pan_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_salaried', models.BooleanField(null=True)),
                ('is_director', models.BooleanField(null=True)),
                ('is_sole_prop', models.BooleanField(null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('less_info', models.BooleanField(null=True)),
                ('profile_match', models.JSONField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(default='INDIA', max_length=100)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pan_details',
            },
        ),
    ]
