# Generated by Django 5.2.6 on 2025-10-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0013_alter_billrequestlog_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="panrequestlog",
            table="kyc_pan_request_log",
        ),
    ]
