# Generated by Django 4.2 on 2025-09-24 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0013_rename_name_vendormanagement_vendor_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendormanagement",
            name="end_point_production",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="end_point_uat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="internal_name",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="production_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="uat_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
