# Generated by Django 5.2 on 2025-09-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0014_pandetails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pandetails',
            table='kyc_pan_details',
        ),
    ]
