# Generated by Django 5.2.6 on 2025-10-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0014_alter_panrequestlog_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="voterdetail",
            table="kyc_voter_detail",
        ),
        migrations.AlterModelTable(
            name="voterrequestlog",
            table="kyc_voter_request_log",
        ),
    ]
