# Generated by Django 5.2.6 on 2025-10-10 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0015_alter_voterdetail_table_alter_voterrequestlog_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BillRequestLog",
            new_name="UatBillRequestLog",
        ),
        migrations.RenameModel(
            old_name="ElectricityBill",
            new_name="UatElectricityBill",
        ),
        migrations.RenameModel(
            old_name="KycNameMatch",
            new_name="UatNameMatch",
        ),
        migrations.RenameModel(
            old_name="NameMatchRequestLog",
            new_name="UatNameMatchRequestLog",
        ),
        migrations.AlterModelTable(
            name="uatbillrequestlog",
            table="uat_bill_request_log",
        ),
        migrations.AlterModelTable(
            name="uatelectricitybill",
            table="uat_bill_details",
        ),
        migrations.AlterModelTable(
            name="uatnamematch",
            table="uat_name_match",
        ),
        migrations.AlterModelTable(
            name="uatnamematchrequestlog",
            table="uat_name_match_request_log",
        ),
    ]
