# Generated by Django 5.2 on 2025-09-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0015_alter_pandetails_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormanagement',
            name='priority',
            field=models.IntegerField(default=30, unique=True),
        ),
    ]
