# Generated by Django 5.2.6 on 2025-10-10 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0016_rename_billrequestlog_uatbillrequestlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PanDetails",
            new_name="UatPanDetails",
        ),
        migrations.RenameModel(
            old_name="PanRequestLog",
            new_name="UatPanRequestLog",
        ),
        migrations.RenameModel(
            old_name="RCDetails",
            new_name="UatRcDetails",
        ),
        migrations.RenameModel(
            old_name="RCRequestLog",
            new_name="UatRcRequestLog",
        ),
        migrations.RenameModel(
            old_name="VoterDetail",
            new_name="UatVoterDetail",
        ),
        migrations.RenameModel(
            old_name="VoterRequestLog",
            new_name="UatVoterRequestLog",
        ),
        migrations.AlterModelTable(
            name="uatpandetails",
            table="uat_pan_details",
        ),
        migrations.AlterModelTable(
            name="uatpanrequestlog",
            table="uat_pan_request_log",
        ),
        migrations.AlterModelTable(
            name="uatrcdetails",
            table="uat_rc_details",
        ),
        migrations.AlterModelTable(
            name="uatrcrequestlog",
            table="uat_rc_request_log",
        ),
        migrations.AlterModelTable(
            name="uatvoterdetail",
            table="uat_voter_detail",
        ),
        migrations.AlterModelTable(
            name="uatvoterrequestlog",
            table="uat_voter_request_log",
        ),
    ]
