# Generated by Django 5.2 on 2025-09-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0016_alter_vendormanagement_priority'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apimanagement',
            table='kyc_api_management',
        ),
        migrations.AlterModelTable(
            name='clientmanagement',
            table='kyc_client_management',
        ),
        migrations.AlterModelTable(
            name='vendormanagement',
            table='kyc_vendor_management',
        ),
    ]
