# Generated by Django 5.2 on 2025-09-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0017_alter_apimanagement_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandetails',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pandetails',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pandetails',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pandetails',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
