# Generated by Django 5.2 on 2025-09-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0018_pandetails_created_by_pandetails_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandetails',
            name='input_dob',
        ),
    ]
