# Generated by Django 5.2.6 on 2025-10-17 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kyc_api_gateway",
            "0018_proelectricitybill_pronamematch_propandetails_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProDrivingLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=100, null=True)),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("dl_number", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("valid_till", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("rto_code", models.CharField(blank=True, max_length=50, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                ("photo", models.TextField(blank=True, null=True)),
                ("signature", models.TextField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "vendor_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("full_response", models.JSONField(blank=True, null=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pro_driving_license",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UatDrivingLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=100, null=True)),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("dl_number", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("valid_till", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("rto_code", models.CharField(blank=True, max_length=50, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                ("photo", models.TextField(blank=True, null=True)),
                ("signature", models.TextField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "vendor_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("full_response", models.JSONField(blank=True, null=True)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "uat_driving_license",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProDrivingLicenseRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("dl_number", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("vendor", models.CharField(blank=True, max_length=100, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("fail", "Fail")],
                        max_length=10,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driving_license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dl_logs",
                        to="kyc_api_gateway.prodrivinglicense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pro_driving_license_request_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UatDrivingLicenseRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("dl_number", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("vendor", models.CharField(blank=True, max_length=100, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("fail", "Fail")],
                        max_length=10,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driving_license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dl_logs",
                        to="kyc_api_gateway.uatdrivinglicense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uat_driving_license_request_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
