# Generated by Django 5.2.5 on 2025-10-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0018_proelectricitybill_pronamematch_propandetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimanagement',
            name='supported_vendors',
        ),
        migrations.RemoveField(
            model_name='clientmanagement',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='clientmanagement',
            name='prod_key',
        ),
        migrations.RemoveField(
            model_name='clientmanagement',
            name='uat_key',
        ),
        migrations.AddField(
            model_name='clientmanagement',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Suspended'), (4, 'Pending'), (5, 'Locked')], default=4),
        ),
        migrations.AddField(
            model_name='vendormanagement',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='apimanagement',
            name='http_method',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apimanagement',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientmanagement',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanagement',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SupportedVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc_api_gateway.apimanagement')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc_api_gateway.vendormanagement')),
            ],
            options={
                'db_table': 'kyc_supported_vendor',
                'unique_together': {('api', 'vendor')},
            },
        ),
    ]
