# Generated by Django 5.2.6 on 2025-10-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0019_prodrivinglicense_uatdrivinglicense_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uatdrivinglicenserequestlog",
            old_name="user",
            new_name="userss",
        ),
    ]
