# Generated by Django 5.2 on 2025-09-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0019_remove_pandetails_input_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendormanagement',
            options={'ordering': ['priority']},
        ),
        migrations.AlterField(
            model_name='vendormanagement',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
