# Generated by Django 5.2 on 2025-10-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0019_remove_apimanagement_supported_vendors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycclientservicesmanagement',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='vendormanagement',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendormanagement',
            name='priority',
        ),
        migrations.AddField(
            model_name='kycclientservicesmanagement',
            name='priority',
            field=models.IntegerField(default=30, unique=True),
        ),
    ]
