# Generated by Django 5.2 on 2025-09-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0020_alter_vendormanagement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormanagement',
            name='end_point_production',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendormanagement',
            name='end_point_uat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendormanagement',
            name='production_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendormanagement',
            name='uat_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
