# Generated by Django 5.2.6 on 2025-10-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0020_rename_user_uatdrivinglicenserequestlog_userss"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uatdrivinglicenserequestlog",
            old_name="userss",
            new_name="user",
        ),
        migrations.AddField(
            model_name="uatdrivinglicense",
            name="dl_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatdrivinglicense",
            name="issuing_authority",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="uatdrivinglicense",
            name="non_transport_validity",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatdrivinglicense",
            name="transport_validity",
            field=models.DateField(blank=True, null=True),
        ),
    ]
