# Generated by Django 4.2 on 2025-10-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0020_alter_kycclientservicesmanagement_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KycVendorPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_priorities",
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
                (
                    "my_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_service_priorities",
                        to="kyc_api_gateway.kycmyservices",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_priority_entries",
                        to="kyc_api_gateway.vendormanagement",
                    ),
                ),
            ],
            options={
                "db_table": "kyc_vendor_priority",
                "ordering": ["priority"],
            },
        ),
    ]
