# Generated by Django 5.2 on 2025-09-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0021_vendormanagement_end_point_production_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandetails',
            name='vendor_source',
        ),
    ]
