# Generated by Django 5.2.6 on 2025-10-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "kyc_api_gateway",
            "0021_rename_userss_uatdrivinglicenserequestlog_user_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="uatdrivinglicenserequestlog",
            old_name="user",
            new_name="users",
        ),
    ]
