# Generated by Django 5.2 on 2025-09-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0022_remove_pandetails_vendor_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendormanagement',
            name='max_retries',
        ),
    ]
