# Generated by Django 5.2.6 on 2025-10-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0022_rename_user_uatdrivinglicenserequestlog_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uatdrivinglicenserequestlog",
            old_name="users",
            new_name="user",
        ),
    ]
