# Generated by Django 4.2 on 2025-10-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kyc_api_gateway",
            "0022_rename_end_point_production_vendormanagement_header_key_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendormanagement",
            name="header_key_name",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="prod_api_key",
            field=models.CharField(default=1234, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="prod_base_url",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="uat_api_key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
