# Generated by Django 5.2.6 on 2025-10-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0023_rename_users_uatdrivinglicenserequestlog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodrivinglicense",
            name="dl_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="prodrivinglicense",
            name="issuing_authority",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="prodrivinglicense",
            name="non_transport_validity",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prodrivinglicense",
            name="transport_validity",
            field=models.DateField(blank=True, null=True),
        ),
    ]
