# Generated by Django 4.2 on 2025-10-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0023_alter_vendormanagement_header_key_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kycvendorpriority",
            unique_together={("client", "vendor", "my_service")},
        ),
    ]
