# Generated by Django 5.2.6 on 2025-10-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0024_prodrivinglicense_dl_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendormanagement",
            old_name="end_point_production",
            new_name="header_key_name",
        ),
        migrations.RenameField(
            model_name="vendormanagement",
            old_name="end_point_uat",
            new_name="prod_api_key",
        ),
        migrations.RenameField(
            model_name="vendormanagement",
            old_name="header",
            new_name="prod_base_url",
        ),
        migrations.RenameField(
            model_name="vendormanagement",
            old_name="production_key",
            new_name="uat_api_key",
        ),
        migrations.RenameField(
            model_name="vendormanagement",
            old_name="uat_key",
            new_name="uat_base_url",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="base_url",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="downtime",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="error_rate",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="health_score",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="response_time",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="secret_key",
        ),
        migrations.RemoveField(
            model_name="vendormanagement",
            name="timeout",
        ),
        migrations.AddField(
            model_name="vendormanagement",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="vendor_name",
            field=models.CharField(max_length=255),
        ),
    ]
