# Generated by Django 4.2 on 2025-10-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0025_alter_kycvendorpriority_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycvendorpriority",
            name="created_by",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="kycvendorpriority",
            name="priority",
            field=models.IntegerField(unique=True),
        ),
    ]
