# Generated by Django 4.2 on 2025-10-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0026_alter_kycvendorpriority_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendormanagement",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="prod_api_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vendormanagement",
            name="prod_base_url",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
